### ISSUE TITLE
Playbook exits by surprise without a license key

### ISSUE THREAD

**Issue by lazzarello** [me-vlad/ansible-role-wowza#3]
While the intended functionality of not installing the Wowza package without a license key is in this role, it fails in a way that does not indicate why it failed.

Add a check for length > 0 of wowza_license_key and stop execution if false.

**Comment by me-vlad** [comment]
wowza_license_key | length > 0 checked in task [Run expect script for WSE install](https://github.com/me-vlad/ansible-role-wowza/blob/69192c10235b1b159b27aa13ae5fb0563d86a5f4/tasks/wowza_install.yml#L29)

To avoid fails with missing or invalid license added info in to [README](https://github.com/me-vlad/ansible-role-wowza/blob/master/README.md)

Thanks!
